services:
  catatan-app:
    build: .
    container_name: catatan_mikrotik_app
    ports:
      - "8080:3000"
    volumes:
      - ./backend/database.sqlite:/app/backend/database.sqlite
    restart: unless-stopped
